
name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: ./mvnw -ntp -B package --file pom.xml -DskipMunitTests
    
    - name: Publish to Exchange
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests \
        -Dclient.id="${{ secrets.ANYPOINT_PLATFORM_USERNAME }}" \
        -Dclient.secret="${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}"

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
        -Dclient.id="${{ secrets.ANYPOINT_PLATFORM_USERNAME }}" \
        -Dclient.secret="${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}"
